# Generated by Django 2.1.1 on 2018-10-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=50)),
                ('upper_limit', models.CharField(max_length=50)),
                ('lower_limit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Chart',
            },
        ),
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('consult_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('patient_user_id', models.IntegerField()),
                ('doctor_user_id', models.IntegerField()),
                ('suggestions_prescriptions', models.TextField(max_length=500)),
                ('health_tips_diets', models.TextField(max_length=500)),
                ('consult_date', models.DateField(max_length=50, null=True)),
                ('next_consult_dates', models.DateField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Consulting',
            },
        ),
        migrations.CreateModel(
            name='lab_tech',
            fields=[
                ('tech_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Lab_technician',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('chart_id', models.IntegerField()),
                ('patient_user_id', models.IntegerField()),
                ('test_result', models.CharField(max_length=50)),
                ('test_date', models.DateField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
