# Generated by Django 2.1.1 on 2018-10-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_date',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
