# Generated by Django 2.1.1 on 2018-10-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('patient_user_id', models.IntegerField()),
                ('doctor_user_id', models.IntegerField()),
                ('appointment_date', models.DateField(max_length=50)),
                ('appointment_time', models.TimeField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'appointment',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='designation',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Laboratory', 'Laboratory'), ('Patient', 'Patient')], max_length=10),
        ),
    ]
