# Generated by Django 2.1.1 on 2018-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('admit_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('patient_user_id', models.IntegerField()),
                ('admit_date', models.DateField(max_length=50)),
                ('discharge_date', models.DateField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Admit_details',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('patient_user_id', models.IntegerField()),
                ('doctor_user_id', models.IntegerField()),
                ('appointment_date', models.DateField(max_length=50)),
                ('appointment_time', models.TimeField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_user_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=35)),
                ('status', models.CharField(choices=[('1', 'Admitted'), ('2', 'Discharged')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Patient_details',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('tech_id', models.IntegerField()),
                ('patient_user_id', models.IntegerField()),
                ('test_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
