# Generated by Django 2.1.1 on 2018-10-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('patient_user_id', models.IntegerField()),
                ('doctor_user_id', models.IntegerField()),
                ('appointment_date', models.DateField(max_length=50)),
                ('appointment_time', models.TimeField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_user_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('timing_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=35)),
                ('photo', models.ImageField(upload_to='')),
                ('specialization', models.CharField(choices=[('1', 'Endocrinologists'), ('2', 'Cardio'), ('3', 'ENT specialist'), ('4', 'Eye specialist')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Doctor_deatails',
            },
        ),
        migrations.CreateModel(
            name='Doctor_timing',
            fields=[
                ('timing_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('available_date', models.DateField(max_length=50)),
                ('available_from', models.TimeField(max_length=50)),
                ('available_to', models.TimeField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Doctor_timing',
            },
        ),
    ]
