# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_timing',
            name=b'doctor_user_id',
        ),
    ]
